### ISSUE TITLE
As a user, if I see a post, I can post in a threaded discussion

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#28]
- First, we'd want to figure out the database table.  Let's put a proposal on github in the issue, communicate about it, before we write the code. 

Example in comment:

| Field Name | Field Type |
| --- | --- |
| id | integer |
- Second, make the full CRUD for a comment.  Allow it to be on a separate page.  Click on a new, and able to see just the form for the comment and submit stuff.

**Comment by ceceliahavens** [comment]
I've feeling overwhelmed by the blank space of where to begin, since this is my flagship issue, If I am off base can you give me a nudge on where to begin?   if a user sees a post they want to comment on, we would need to reference the original post which is tied to the original user id, so our new post would be linked to both the current user and thus that user's ID (because it is tied to the original comment).   We will need a place to store the comment text, the original comment and the  current user.   Am I missing anything for our comment field?

**Comment by kenmazaika** [comment]
I think you're pretty close to on point with where you should be.  My advice is to translate your working of the stuff we'll need in the database table to a list of the fields along with the data types it should be.

It probably will look pretty close to the `comment` model in nomster, or that's where I might look for inspiration.

**Comment by ceceliahavens** [comment]
| Fields | Data Type |
| --- | --- |
| Message | Text |
| User_id | Integer |
| post_id | integer |

I am not sure of the appropriate verbiage for the post_id.  Am I correct to assume that will tie our comment to the original post?

**Comment by kenmazaika** [comment]
Looks good to me.  I think that makes sense!
