### ISSUE TITLE
After a post is create email notifications should go out

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#39]
Initially let's make the emails go out to all users.

**Comment by ceceliahavens** [comment]
Do you remember when you were in school and a teacher called on you, but you weren't actually paying attention, and you panicked a little?  Well funny story......I was trying to get my DEFCON app open when you were discussing this ticket and I wasn't really paying any attention. (some things never change)  Can I get some clarification on what it is I signed up for?  Because if we leave it up to me to decide, it will probably be way more fun, but not at all what we are looking for.   I have lots of visions and most of them are a little wrong.  I mean if I am in charge of spamming a group........I'm pretty sure it would involve David Hasselhoff, which is probably not what was being discussed while I was not paying attention.   I don't know what is says about me, but I'd kind of like to be spammed/hassled by the Hoff. 
![david-hasselhoff-hugging-puppies_zpsee42f8ca](https://cloud.githubusercontent.com/assets/14093756/12076229/ecf612f0-b167-11e5-8ced-bee647a7efda.jpg)

**Comment by kenmazaika** [comment]
I love the image!

When a user creates a post, initially all users in our database should receive an email notification so they know they should come to the platform and check it out.  It's our version of this in Google+

![screen shot 2016-01-02 at 7 24 51 pm](https://cloud.githubusercontent.com/assets/233615/12076733/919b78e0-b186-11e5-9301-6e5bfb7efb79.png)

**Comment by ceceliahavens** [comment]
I am over the moon about how much those puppies seem to hate the Hoff, and I will hopefully get started on this tomorrow. Thanks for the clarification!
