### ISSUE TITLE
Styling is a bit off on the posts/index page

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#41]
Cleaning that up a little could make it look better.

**Comment by Matt-Lepley** [comment]
PR: https://github.com/FirehoseCommunity/DEFCON/pull/52

Made the header and button centered and not stuck on other divs:

![image](https://cloud.githubusercontent.com/assets/11146542/12096094/0bfb319c-b2e1-11e5-84e1-97aa3985051f.png)

Adjusted the submit modal since we had buttons not working / not in use:

![image](https://cloud.githubusercontent.com/assets/11146542/12096111/233ed25a-b2e1-11e5-8884-38ea3183e69a.png)
