### ISSUE TITLE
The topnav should have a pop-down menu

### ISSUE THREAD

**Issue by kenmazaika** [FirehoseCommunity/DEFCON#87]
Like in the wireframes.

**Comment by ceceliahavens** [comment]
Could you please clarify for me? I have just looked at the wireframes but I am not clear on what we are looking for here.  Thanks!

**Comment by kenmazaika** [comment]
The wireframes indicate that on the top right there should be a dropdown menu like here:

https://getbootstrap.com/examples/navbar/

**Comment by amarkpark** [comment]
@ceceliahavens You can look at (or steal) the dropdown that I have as the Admin Menu... https://github.com/FirehoseCommunity/DEFCON/blob/master/app/views/layouts/_adminmenu.html.haml
Right now there is only one functional link in there, it was just something I added for grouping together admin stuff but we can actually move that whole menu into the main navbar and change out current placeholder links for live nav links and change it so the admin stuff is just hidden by logic in one of the separator sections maybe...? I made the admin menu partial before I thought too closely about the wireframe layout. The admin link(s) can be hidden instead of having a hidden partial...?

**Comment by ceceliahavens** [comment]
Thanks @amarkpark I already implemented one before I read your offer!  @kenmazaika, what is supposed to be included in the drop down? That is the part I was unclear on. I've committed to the dropdown branch the skeletal structure of a dropdown, which just took me a minute to do, but I am not sure by the wireframes what the dropdown is supposed to include.  I'll use the dropdown branch as the place holder until I get a little clarification. thanks!

**Comment by kenmazaika** [comment]
I believe the wireframes I have include the items that it should have.  Take a look there.  I think it has "Sign in" and "Sign out" in a popup along with the user name.

**Comment by ceceliahavens** [comment]
Thanks, those were floating off to the side and it said "pop up" so i wasn't sure if that was something else we were after.  I'll get it taken care of straight away.

**Comment by kenmazaika** [comment]
Thanks, @ceceliahavens!

**Comment by kenmazaika** [comment]
Implemented!
